// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bills.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bills (user_id, name, category, service_provider, expected_amount, due_day)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, category, service_provider, expected_amount, due_day, status, created_at, updated_at
`

type CreateBillParams struct {
	UserID          pgtype.UUID    `json:"user_id"`
	Name            string         `json:"name"`
	Category        string         `json:"category"`
	ServiceProvider string         `json:"service_provider"`
	ExpectedAmount  pgtype.Numeric `json:"expected_amount"`
	DueDay          int16          `json:"due_day"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.UserID,
		arg.Name,
		arg.Category,
		arg.ServiceProvider,
		arg.ExpectedAmount,
		arg.DueDay,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.ServiceProvider,
		&i.ExpectedAmount,
		&i.DueDay,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBill = `-- name: DeleteBill :exec
DELETE FROM bills
WHERE id = $1 AND user_id = $2
`

type DeleteBillParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteBill(ctx context.Context, arg DeleteBillParams) error {
	_, err := q.db.Exec(ctx, deleteBill, arg.ID, arg.UserID)
	return err
}

const getBillByID = `-- name: GetBillByID :one
SELECT id, user_id, name, category, service_provider, expected_amount, due_day, status, created_at, updated_at FROM bills
WHERE id = $1 AND user_id = $2
`

type GetBillByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetBillByID(ctx context.Context, arg GetBillByIDParams) (Bill, error) {
	row := q.db.QueryRow(ctx, getBillByID, arg.ID, arg.UserID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.ServiceProvider,
		&i.ExpectedAmount,
		&i.DueDay,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBillsByUser = `-- name: ListBillsByUser :many
SELECT id, user_id, name, category, service_provider, expected_amount, due_day, status, created_at, updated_at FROM bills
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBillsByUser(ctx context.Context, userID pgtype.UUID) ([]Bill, error) {
	rows, err := q.db.Query(ctx, listBillsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Category,
			&i.ServiceProvider,
			&i.ExpectedAmount,
			&i.DueDay,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBill = `-- name: UpdateBill :one
UPDATE bills
SET name = $3,
    category = $4,
    service_provider = $5,
    expected_amount = $6,
    due_day = $7,
    status = $8,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, category, service_provider, expected_amount, due_day, status, created_at, updated_at
`

type UpdateBillParams struct {
	ID              pgtype.UUID    `json:"id"`
	UserID          pgtype.UUID    `json:"user_id"`
	Name            string         `json:"name"`
	Category        string         `json:"category"`
	ServiceProvider string         `json:"service_provider"`
	ExpectedAmount  pgtype.Numeric `json:"expected_amount"`
	DueDay          int16          `json:"due_day"`
	Status          string         `json:"status"`
}

func (q *Queries) UpdateBill(ctx context.Context, arg UpdateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, updateBill,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Category,
		arg.ServiceProvider,
		arg.ExpectedAmount,
		arg.DueDay,
		arg.Status,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.ServiceProvider,
		&i.ExpectedAmount,
		&i.DueDay,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
