// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (bill_id, month, amount_paid, proof_file_url)
VALUES ($1, $2, $3, $4)
RETURNING id, bill_id, month, amount_paid, proof_file_url, paid_at
`

type CreatePaymentParams struct {
	BillID       pgtype.UUID    `json:"bill_id"`
	Month        string         `json:"month"`
	AmountPaid   pgtype.Numeric `json:"amount_paid"`
	ProofFileUrl pgtype.Text    `json:"proof_file_url"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BillID,
		arg.Month,
		arg.AmountPaid,
		arg.ProofFileUrl,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.Month,
		&i.AmountPaid,
		&i.ProofFileUrl,
		&i.PaidAt,
	)
	return i, err
}

const getPaymentByBillAndMonth = `-- name: GetPaymentByBillAndMonth :one
SELECT id, bill_id, month, amount_paid, proof_file_url, paid_at FROM payments
WHERE bill_id = $1 AND month = $2
`

type GetPaymentByBillAndMonthParams struct {
	BillID pgtype.UUID `json:"bill_id"`
	Month  string      `json:"month"`
}

func (q *Queries) GetPaymentByBillAndMonth(ctx context.Context, arg GetPaymentByBillAndMonthParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByBillAndMonth, arg.BillID, arg.Month)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.Month,
		&i.AmountPaid,
		&i.ProofFileUrl,
		&i.PaidAt,
	)
	return i, err
}

const listPaymentsByUserAndMonth = `-- name: ListPaymentsByUserAndMonth :many
SELECT p.id, p.bill_id, p.month, p.amount_paid, p.proof_file_url, p.paid_at FROM payments p
INNER JOIN bills b ON b.id = p.bill_id
WHERE b.user_id = $1 AND p.month = $2
`

type ListPaymentsByUserAndMonthParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Month  string      `json:"month"`
}

func (q *Queries) ListPaymentsByUserAndMonth(ctx context.Context, arg ListPaymentsByUserAndMonthParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUserAndMonth, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.Month,
			&i.AmountPaid,
			&i.ProofFileUrl,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
