// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBill(ctx context.Context, arg DeleteBillParams) error
	GetBillByID(ctx context.Context, arg GetBillByIDParams) (Bill, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListBillsByUser(ctx context.Context, userID pgtype.UUID) ([]Bill, error)
	UpdateBill(ctx context.Context, arg UpdateBillParams) (Bill, error)
}

var _ Querier = (*Queries)(nil)
